from PlayerQuery import pq # pq(<Player>)
from News import news # news()
from VersionInfo import ver # ver(<Number>)
from FeatureQuery import bug # bug(<ID>)
from WikiQuery import wiki # wiki(<Content>)
from ServerQuery import sq # sq() with window
# ----- Part 1 -----
from ModDecompileHelper import mdk # mdk() with window
from ModID import dirget # dirget(<Dir>)
from MavenDownload import maven # maven() with window
from MCrFileGenerator import mfg # mfg(file, modid, modname, ver, author, url, generator, package, mcrver)
from UnicodeConvert import * # char2unicode(<String>), unicode2char(<String>)
# ----- Part 2 -----
from MinecraftPython import mc # mc() with window
from AdvancementGen import adv # adv(pic, text1, text2, file)
from GoogleGrassMaker import google # google() with window
from YiYan import yiyan # yiyan() with window
from Downloader import down # down() with window
from SystemInfo import system_info # system_info() with window
from Roman import rm # rm(<Number>)
from ColorConverter import cc # cc() with window
# ----- Part 3 -----
from tkinter import *
# Can use MojangAPI to get more data, but I'm too lazy
t = Tk()
t.title('Minecraft Helper')
def player_quest():
    t2 = Tk()
    t2.title('玩家查询')
    l1_2 = Label(t2, text = '玩家名')
    l1_2.grid(row = 0, column = 0)
    e1_2 = Entry(t2)
    e1_2.grid(row = 0, column = 1)
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        t1_2.insert('end', pq(e1_2.get()))
    b1_2 = Button(t2, text = '查询', command = process)
    b1_2.grid(row = 1, column = 0, columnspan = 2)
    t1_2.grid(row = 2, column = 0, columnspan = 2)
    t2.mainloop()
l1 = Label(t, text = '查询类')
l1.grid(row = 0, column = 0, columnspan = 5, sticky = N + S + E + W)
b1 = Button(t, text = '玩家查询', command = player_quest, height = 2, width = 10)
b1.grid(row = 1, column = 0)
def news_quest():
    t2 = Tk()
    t2.title('新闻查询')
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        t1_2.insert('end', news())
    b1_2 = Button(t2, text = '查询(时间较长，请等待)', command = process)
    b1_2.grid(row = 0, column = 0)
    t1_2.grid(row = 1, column = 0)
    t2.mainloop()
b2 = Button(t, text = '新闻查询', command = news_quest, height = 2, width = 10)
b2.grid(row = 1, column = 1)
def version_info():
    t2 = Tk()
    t2.title('版本信息查询')
    l1_2 = Label(t2, text = '版本列表个数')
    l1_2.grid(row = 0, column = 0)
    e1_2 = Entry(t2)
    e1_2.grid(row = 0, column = 1)
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        t1_2.insert('end', ver(int(e1_2.get())))
    b1_2 = Button(t2, text = '查询', command = process)
    b1_2.grid(row = 1, column = 0, columnspan = 2)
    t1_2.grid(row = 2, column = 0, columnspan = 2)
    t2.mainloop()
b3 = Button(t, text = '版本信息', command = version_info, height = 2, width = 10)
b3.grid(row = 1, column = 2)
def bug_query():
    t2 = Tk()
    t2.title('特性查询')
    l1_2 = Label(t2, text = '特性编号')
    l1_2.grid(row = 0, column = 0)
    e1_2 = Entry(t2)
    e1_2.grid(row = 0, column = 1)
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        t1_2.insert('end', bug(e1_2.get()))
    b1_2 = Button(t2, text = '查询', command = process)
    b1_2.grid(row = 1, column = 0, columnspan = 2)
    t1_2.grid(row = 2, column = 0, columnspan = 2)
    t2.mainloop()
b4 = Button(t, text = '特性查询', command = bug_query, height = 2, width = 10)
b4.grid(row = 1, column = 3)
def wiki_query():
    t2 = Tk()
    t2.title('MCWiki查询')
    l1_2 = Label(t2, text = '词条')
    l1_2.grid(row = 0, column = 0)
    e1_2 = Entry(t2)
    e1_2.grid(row = 0, column = 1)
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        t1_2.insert('end', wiki(e1_2.get()))
    b1_2 = Button(t2, text = '查询', command = process)
    b1_2.grid(row = 1, column = 0, columnspan = 2)
    t1_2.grid(row = 2, column = 0, columnspan = 2)
    t2.mainloop()
b5 = Button(t, text = 'Wiki查询', command = wiki_query, height = 2, width = 10)
b5.grid(row = 1, column = 4)
b18 = Button(t, text = '服务器信息', command = sq, height = 2, width = 10)
b18.grid(row = 2, column = 0, columnspan = 5)
l2 = Label(t, text = 'Mod开发')
l2.grid(row = 3, column = 0, columnspan = 5, sticky = N + S + E + W)
b6 = Button(t, text = 'Mod反编译', command = mdk, height = 2, width = 10)
b6.grid(row = 4, column = 0)
def modid_query():
    t2 = Tk()
    t2.title('Mod文件信息')
    l1_2 = Label(t2, text = 'Mod文件目录')
    l1_2.grid(row = 0, column = 0)
    e1_2 = Entry(t2)
    e1_2.grid(row = 0, column = 1)
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        t1_2.insert('end', dirget(e1_2.get()))
    b1_2 = Button(t2, text = '获取', command = process)
    b1_2.grid(row = 1, column = 0, columnspan = 2)
    t1_2.grid(row = 2, column = 0, columnspan = 2)
    t2.mainloop()
b7 = Button(t, text = 'ModID查询', command = modid_query, height = 2, width = 10)
b7.grid(row = 4, column = 1)
b8 = Button(t, text = 'Maven库下载', command = maven, height = 2, width = 10)
b8.grid(row = 4, column = 2)
def file_gen():
    t2 = Tk()
    t2.title('MCr工作区文件生成')
    l1_2 = Label(t2, text = '文件名')
    l1_2.grid(row = 0, column = 0)
    e1_2 = Entry(t2)
    e1_2.grid(row = 0, column = 1)
    l2_2 = Label(t2, text = '模组ID')
    l2_2.grid(row = 1, column = 0)
    e2_2 = Entry(t2)
    e2_2.grid(row = 1, column = 1)
    l3_2 = Label(t2, text = '模组名')
    l3_2.grid(row = 2, column = 0)
    e3_2 = Entry(t2)
    e3_2.grid(row = 2, column = 1)
    l4_2 = Label(t2, text = '模组版本')
    l4_2.grid(row = 3, column = 0)
    e4_2 = Entry(t2)
    e4_2.grid(row = 3, column = 1)
    l5_2 = Label(t2, text = '作者')
    l5_2.grid(row = 4, column = 0)
    e5_2 = Entry(t2)
    e5_2.grid(row = 4, column = 1)
    l6_2 = Label(t2, text = 'URL')
    l6_2.grid(row = 5, column = 0)
    e6_2 = Entry(t2)
    e6_2.grid(row = 5, column = 1)
    l7_2 = Label(t2, text = 'Mod生成器版本')
    l7_2.grid(row = 6, column = 0)
    e7_2 = Entry(t2)
    e7_2.grid(row = 6, column = 1)
    l8_2 = Label(t2, text = '模组包名')
    l8_2.grid(row = 7, column = 0)
    e8_2 = Entry(t2)
    e8_2.grid(row = 7, column = 1)
    l9_2 = Label(t2, text = 'MCr版本(主版本+0+副版本+开发版本)')
    l9_2.grid(row = 8, column = 0)
    e9_2 = Entry(t2)
    e9_2.grid(row = 8, column = 1)
    def process():
        mfg(e1_2.get(), e2_2.get(), e3_2.get(), e4_2.get(), e5_2.get(), e6_2.get(), e7_2.get(), e8_2.get(), e9_2.get())
    b1_2 = Button(t2, text = '生成', command = process)
    b1_2.grid(row = 9, column = 0, columnspan = 2)
    t2.mainloop()
b9 = Button(t, text = '工作区文件生成', command = file_gen, height = 2, width = 10)
b9.grid(row = 4, column = 3)
def conv():
    t2 = Tk()
    t2.title('Unicode转换')
    v1_2 = IntVar()
    v1_2.set(1)
    def c1():
        v1_2.set(1)
    def c2():
        v1_2.set(2)
    r1_2 = Radiobutton(t2, text = '字符转Unicode', variable = v1_2, value = 1, command = c1)
    r2_2 = Radiobutton(t2, text = 'Unicode转字符', variable = v1_2, value = 2, command = c2)
    r1_2.grid(row = 0, column = 0)
    r2_2.grid(row = 0, column = 1)
    e1_2 = Entry(t2)
    e1_2.grid(row = 1, column = 0, columnspan = 2)
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        if v1_2.get() == 1:
            t1_2.insert('end', char2unicode(e1_2.get()))
        elif v1_2.get() == 2:
            ans = unicode2char(e1_2.get())
            if ans:
                t1_2.insert('end', ans)
            else:
                t1_2.insert('end', 'Invalid string!')
    b1_2 = Button(t2, text = '转换', command = process)
    b1_2.grid(row = 2, column = 0, columnspan = 2)
    t1_2.grid(row = 3, column = 0, columnspan = 2)
    t2.mainloop()
b10 = Button(t, text = 'Unicode转换', command = conv, height = 2, width = 10)
b10.grid(row = 4, column = 4)
l3 = Label(t, text = '休闲')
l3.grid(row = 5, column = 0, columnspan = 5, sticky = N + S + E + W)
def mc2():
    t2 = Tk()
    t2.title('MC in py')
    l1_2 = Label(t2, text = '说明：\n1:砖 2:草方块 3:沙子 4:边界（特供）\n左键破坏 右键放置 W前进 S后退 A向左 D向右\n空格跳跃 Esc退出 Tab切换飞行（WASD控制方向） R切换边界破坏（特供）')
    l1_2.pack()
    b1_2 = Button(t2, text = '启动', command = mc)
    b1_2.pack()
    t2.mainloop()
b11 = Button(t, text = 'MC in py', command = mc2, height = 2, width = 10)
b11.grid(row = 6, column = 0)
def ag():
    t2 = Tk()
    t2.title('进度生成器')
    l1_2 = Label(t2, text = '图标名称（物品英文）')
    l1_2.grid(row = 0, column = 0)
    e1_2 = Entry(t2)
    e1_2.grid(row = 0, column = 1)
    l2_2 = Label(t2, text = '文本1')
    l2_2.grid(row = 1, column = 0)
    e2_2 = Entry(t2)
    e2_2.grid(row = 1, column = 1)
    l3_2 = Label(t2, text = '文本2')
    l3_2.grid(row = 2, column = 0)
    e3_2 = Entry(t2)
    e3_2.grid(row = 2, column = 1)
    l4_2 = Label(t2, text = '保存文件名')
    l4_2.grid(row = 3, column = 0)
    e4_2 = Entry(t2)
    e4_2.grid(row = 3, column = 1)
    def process():
        adv(e1_2.get(), e2_2.get(), e3_2.get(), './adv-maker/' + e4_2.get() + '.png')
    b1_2 = Button(t2, text = '生成', command = process)
    b1_2.grid(row = 4, column = 0, columnspan = 2)
    t2.mainloop()
b12 = Button(t, text = '进度生成器', command = ag, height = 2, width = 10)
b12.grid(row = 6, column = 1)
b13 = Button(t, text = '谷歌生草机', command = google, height = 2, width = 10)
b13.grid(row = 6, column = 2)
b14 = Button(t, text = '一言', command = yiyan, height = 2, width = 10)
b14.grid(row = 6, column = 3)
b15 = Button(t, text = '下载器', command = down, height = 2, width = 10)
b15.grid(row = 6, column = 4)
b16 = Button(t, text = '系统信息', command = system_info, height = 2, width = 10)
b16.grid(row = 7, column = 0)
def roman():
    t2 = Tk()
    t2.title('罗马数字转换')
    e1_2 = Entry(t2)
    e1_2.pack()
    t1_2 = Text(t2)
    def process():
        t1_2.delete(1.0, 'end')
        t1_2.insert('end', rm(int(e1_2.get())))
    b1_2 = Button(t2, text = '转换', command = process)
    b1_2.pack()
    t1_2.pack()
    t2.mainloop()
b17 = Button(t, text = '罗马数字', command = roman, height = 2, width = 10)
b17.grid(row = 7, column = 2)
b19 = Button(t, text = '格式字符转换', command = cc, height = 2, width = 10)
b19.grid(row = 7, column = 4)
t.mainloop()
